repo: gardusig/static-puzzles-frontend
jobs:
- id: lint
  name: Repo lint
  target: lint
- id: repo-hygiene
  name: Repo structure
  target: repo-hygiene
  needs: lint
  hygiene_policy:
    max_depth: 8
    allowed_root_dirs:
    - .github
    - .workflows
    - scripts
    - src
    - test
    allowed_root_files:
    - .gitignore
    - Dockerfile
    - LICENSE
    - Makefile
    - README.md
    allowed_extensions:
    - .css
    - .html
    - .js
    - .jsx
    - .json
    - .md
    - .sh
    - .yaml
    - .yml
    allowed_filenames:
    - .gitignore
    - Dockerfile
    - LICENSE
    - Makefile
    allowed_paths:
    - .github/pull-request.yaml
